language: python
python:
  - "2.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script:
  - nosetests --with-coverage --cover-erase --cover-package=twseia