language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
# command to run tests
script:
  - nosetests --cover-erase --with-coverage
  - sphinx-apidoc -M -E -f -o docs/source twseia
  - sphinx-build docs/source docs/build/html
  - coveralls --verbose